FOLLOW_SETS = {
    'PG': {'$'},
    'B': {'dot'},
    'VAR_DECL_PART_OPT': {'procedure', 'start_command'},
    'VAR_DECL_STMT': {'int', 'boolean', 'procedure', 'start_command'},
    'TYPE': {'identifier'},
    'L_ID': {'semicolon', 'colon', 
             'multiply', 'divide', 'and', 'plus', 'minus', 'or', 
             'equals', 'not_equals', 'lt', 'lte', 'gt', 'gte', 
             'left_parenteses', 'right_parenteses',
             'execute_conditional', 'execute_loop', 'comma', 
             'end_command', 'otherwise_conditional', 'assignment_operator'},
    'L_ID_MORE': {'semicolon', 'colon',
                  'multiply', 'divide', 'and', 'plus', 'minus', 'or',
                  'equals', 'not_equals', 'lt', 'lte', 'gt', 'gte',
                  'left_parenteses', 'right_parenteses',
                  'execute_conditional', 'execute_loop', 'comma',
                  'end_command', 'otherwise_conditional', 'assignment_operator'},
    'D_SUB_P_OPT': {'start_command', 'dot'},
    'D_PROC': {'semicolon', 'start_command', 'dot'},
    'P_FORM_OPT': {'semicolon'},
    'P_FORM': {'semicolon'},
    'S_P_FORM_LIST': {'left_parenteses'},
    'S_P_FORM_LINE': {'variable', 'identifier', 'left_parenteses', 'semicolon'}, 
    'semicolon_opt': {'variable', 'identifier', 'left_parenteses'},
    'S_P_FORM': {'semicolon', 'variable', 'identifier', 'left_parenteses'},
    'VAR_OPT': {'identifier'},
    'C_COMP': {'dot', 'semicolon', 'end_command', 'otherwise_conditional'},
    'CMD_LIST': {'end_command'},
    'CMD_TAIL': {'end_command'},
    'CMD': {'semicolon', 'end_command', 'otherwise_conditional'},
    'ID_CMD': {'semicolon', 'end_command', 'otherwise_conditional'},
    'L_EXP_OPT': {'left_parenteses'},
    'ASSIGN_OPT': {'semicolon', 'end_command', 'otherwise_conditional'},
    'NO_PAREN_TAIL': {'semicolon', 'end_command', 'otherwise_conditional'},
    'C_COND': {'semicolon', 'end_command', 'otherwise_conditional'},
    'ELSE_OPT': {'semicolon', 'end_command', 'otherwise_conditional'},
    'C_REP': {'semicolon', 'end_command', 'otherwise_conditional'},
    'L_EXP': {'comma', 'left_parenteses'},
    'L_EXP_TAIL': {'comma', 'left_parenteses'},
    'EXP': {'equals', 'not_equals', 'lt', 'lte', 'gt', 'gte', 
            'comma', 'left_parenteses', 'execute_conditional', 'execute_loop', 
            'semicolon', 'end_command', 'otherwise_conditional'},
    'EXP_TAIL': {'equals', 'not_equals', 'lt', 'lte', 'gt', 'gte', 
                 'comma', 'left_parenteses', 'execute_conditional', 'execute_loop', 
                 'semicolon', 'end_command', 'otherwise_conditional'},
    'REL': {'plus', 'minus', 'identifier', 'integer', 'real', 'true', 'false', 'right_parenteses', 'not'},
    'EXP_S': {'equals', 'not_equals', 'lt', 'lte', 'gt', 'gte', 
              'comma', 'left_parenteses', 'execute_conditional', 'execute_loop', 
              'semicolon', 'end_command', 'otherwise_conditional'},
    'TERM_OPT_SIGN': {'identifier', 'integer', 'real', 'true', 'false', 'right_parenteses', 'not'},
    'TERM': {'plus', 'minus', 'or', 'equals', 'not_equals', 'lt', 'lte', 'gt', 'gte', 
             'comma', 'left_parenteses', 'execute_conditional', 'execute_loop', 
             'semicolon', 'end_command', 'otherwise_conditional'},
    'TERM_TAIL': {'plus', 'minus', 'or', 'equals', 'not_equals', 'lt', 'lte', 'gt', 'gte', 
                  'comma', 'left_parenteses', 'execute_conditional', 'execute_loop', 
                  'semicolon', 'end_command', 'otherwise_conditional'},
    'ADD_OP': {'identifier', 'integer', 'real', 'true', 'false', 'right_parenteses', 'not'},
    'FAT': {'multiply', 'divide', 'and', 'plus', 'minus', 'or', 
            'equals', 'not_equals', 'lt', 'lte', 'gt', 'gte', 
            'comma', 'left_parenteses', 'execute_conditional', 'execute_loop', 
            'semicolon', 'end_command', 'otherwise_conditional'},
    'FAT_TAIL': {'multiply', 'divide', 'and', 'plus', 'minus', 'or', 
                 'equals', 'not_equals', 'lt', 'lte', 'gt', 'gte', 
                 'comma', 'left_parenteses', 'execute_conditional', 'execute_loop', 
                 'semicolon', 'end_command', 'otherwise_conditional'},
    'MULT_OP': {'identifier', 'integer', 'real', 'true', 'false', 'right_parenteses', 'not'},
    'VAR_ACCESS': {'multiply', 'divide', 'and', 'plus', 'minus', 'or', 
                   'equals', 'not_equals', 'lt', 'lte', 'gt', 'gte', 
                   'comma', 'left_parenteses', 'execute_conditional', 'execute_loop', 
                   'semicolon', 'end_command', 'otherwise_conditional'},
}

def get_follow_set():
    return FOLLOW_SETS